# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001/CMakeFiles /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runPlayerTests

# Build rule for target.
runPlayerTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runPlayerTests
.PHONY : runPlayerTests

# fast build rule for target.
runPlayerTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/build
.PHONY : runPlayerTests/fast

#=============================================================================
# Target rules for targets named runEnemyTests

# Build rule for target.
runEnemyTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runEnemyTests
.PHONY : runEnemyTests

# fast build rule for target.
runEnemyTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/build
.PHONY : runEnemyTests/fast

#=============================================================================
# Target rules for targets named runBattleTests

# Build rule for target.
runBattleTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runBattleTests
.PHONY : runBattleTests

# fast build rule for target.
runBattleTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/build
.PHONY : runBattleTests/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/BattleTime.o: src/BattleTime.cpp.o
.PHONY : src/BattleTime.o

# target to build an object file
src/BattleTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/BattleTime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/BattleTime.cpp.o
.PHONY : src/BattleTime.cpp.o

src/BattleTime.i: src/BattleTime.cpp.i
.PHONY : src/BattleTime.i

# target to preprocess a source file
src/BattleTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/BattleTime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/BattleTime.cpp.i
.PHONY : src/BattleTime.cpp.i

src/BattleTime.s: src/BattleTime.cpp.s
.PHONY : src/BattleTime.s

# target to generate assembly for a file
src/BattleTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/BattleTime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/BattleTime.cpp.s
.PHONY : src/BattleTime.cpp.s

src/Enemy.o: src/Enemy.cpp.o
.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/Enemy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/Enemy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i
.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/Enemy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/Enemy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s
.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/Enemy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/Enemy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/Items/Armors/Armor.o: src/Items/Armors/Armor.cpp.o
.PHONY : src/Items/Armors/Armor.o

# target to build an object file
src/Items/Armors/Armor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Armor.cpp.o
.PHONY : src/Items/Armors/Armor.cpp.o

src/Items/Armors/Armor.i: src/Items/Armors/Armor.cpp.i
.PHONY : src/Items/Armors/Armor.i

# target to preprocess a source file
src/Items/Armors/Armor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Armor.cpp.i
.PHONY : src/Items/Armors/Armor.cpp.i

src/Items/Armors/Armor.s: src/Items/Armors/Armor.cpp.s
.PHONY : src/Items/Armors/Armor.s

# target to generate assembly for a file
src/Items/Armors/Armor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Armor.cpp.s
.PHONY : src/Items/Armors/Armor.cpp.s

src/Items/Armors/Dragonsbane.o: src/Items/Armors/Dragonsbane.cpp.o
.PHONY : src/Items/Armors/Dragonsbane.o

# target to build an object file
src/Items/Armors/Dragonsbane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Dragonsbane.cpp.o
.PHONY : src/Items/Armors/Dragonsbane.cpp.o

src/Items/Armors/Dragonsbane.i: src/Items/Armors/Dragonsbane.cpp.i
.PHONY : src/Items/Armors/Dragonsbane.i

# target to preprocess a source file
src/Items/Armors/Dragonsbane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Dragonsbane.cpp.i
.PHONY : src/Items/Armors/Dragonsbane.cpp.i

src/Items/Armors/Dragonsbane.s: src/Items/Armors/Dragonsbane.cpp.s
.PHONY : src/Items/Armors/Dragonsbane.s

# target to generate assembly for a file
src/Items/Armors/Dragonsbane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Dragonsbane.cpp.s
.PHONY : src/Items/Armors/Dragonsbane.cpp.s

src/Items/Armors/Obsidiansentinel.o: src/Items/Armors/Obsidiansentinel.cpp.o
.PHONY : src/Items/Armors/Obsidiansentinel.o

# target to build an object file
src/Items/Armors/Obsidiansentinel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Obsidiansentinel.cpp.o
.PHONY : src/Items/Armors/Obsidiansentinel.cpp.o

src/Items/Armors/Obsidiansentinel.i: src/Items/Armors/Obsidiansentinel.cpp.i
.PHONY : src/Items/Armors/Obsidiansentinel.i

# target to preprocess a source file
src/Items/Armors/Obsidiansentinel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Obsidiansentinel.cpp.i
.PHONY : src/Items/Armors/Obsidiansentinel.cpp.i

src/Items/Armors/Obsidiansentinel.s: src/Items/Armors/Obsidiansentinel.cpp.s
.PHONY : src/Items/Armors/Obsidiansentinel.s

# target to generate assembly for a file
src/Items/Armors/Obsidiansentinel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Armors/Obsidiansentinel.cpp.s
.PHONY : src/Items/Armors/Obsidiansentinel.cpp.s

src/Items/Items.o: src/Items/Items.cpp.o
.PHONY : src/Items/Items.o

# target to build an object file
src/Items/Items.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Items.cpp.o
.PHONY : src/Items/Items.cpp.o

src/Items/Items.i: src/Items/Items.cpp.i
.PHONY : src/Items/Items.i

# target to preprocess a source file
src/Items/Items.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Items.cpp.i
.PHONY : src/Items/Items.cpp.i

src/Items/Items.s: src/Items/Items.cpp.s
.PHONY : src/Items/Items.s

# target to generate assembly for a file
src/Items/Items.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Items.cpp.s
.PHONY : src/Items/Items.cpp.s

src/Items/Potions/GreaterHealthPotion.o: src/Items/Potions/GreaterHealthPotion.cpp.o
.PHONY : src/Items/Potions/GreaterHealthPotion.o

# target to build an object file
src/Items/Potions/GreaterHealthPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/GreaterHealthPotion.cpp.o
.PHONY : src/Items/Potions/GreaterHealthPotion.cpp.o

src/Items/Potions/GreaterHealthPotion.i: src/Items/Potions/GreaterHealthPotion.cpp.i
.PHONY : src/Items/Potions/GreaterHealthPotion.i

# target to preprocess a source file
src/Items/Potions/GreaterHealthPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/GreaterHealthPotion.cpp.i
.PHONY : src/Items/Potions/GreaterHealthPotion.cpp.i

src/Items/Potions/GreaterHealthPotion.s: src/Items/Potions/GreaterHealthPotion.cpp.s
.PHONY : src/Items/Potions/GreaterHealthPotion.s

# target to generate assembly for a file
src/Items/Potions/GreaterHealthPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/GreaterHealthPotion.cpp.s
.PHONY : src/Items/Potions/GreaterHealthPotion.cpp.s

src/Items/Potions/LesserHealthPotion.o: src/Items/Potions/LesserHealthPotion.cpp.o
.PHONY : src/Items/Potions/LesserHealthPotion.o

# target to build an object file
src/Items/Potions/LesserHealthPotion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/LesserHealthPotion.cpp.o
.PHONY : src/Items/Potions/LesserHealthPotion.cpp.o

src/Items/Potions/LesserHealthPotion.i: src/Items/Potions/LesserHealthPotion.cpp.i
.PHONY : src/Items/Potions/LesserHealthPotion.i

# target to preprocess a source file
src/Items/Potions/LesserHealthPotion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/LesserHealthPotion.cpp.i
.PHONY : src/Items/Potions/LesserHealthPotion.cpp.i

src/Items/Potions/LesserHealthPotion.s: src/Items/Potions/LesserHealthPotion.cpp.s
.PHONY : src/Items/Potions/LesserHealthPotion.s

# target to generate assembly for a file
src/Items/Potions/LesserHealthPotion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/LesserHealthPotion.cpp.s
.PHONY : src/Items/Potions/LesserHealthPotion.cpp.s

src/Items/Potions/Potion.o: src/Items/Potions/Potion.cpp.o
.PHONY : src/Items/Potions/Potion.o

# target to build an object file
src/Items/Potions/Potion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/Potion.cpp.o
.PHONY : src/Items/Potions/Potion.cpp.o

src/Items/Potions/Potion.i: src/Items/Potions/Potion.cpp.i
.PHONY : src/Items/Potions/Potion.i

# target to preprocess a source file
src/Items/Potions/Potion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/Potion.cpp.i
.PHONY : src/Items/Potions/Potion.cpp.i

src/Items/Potions/Potion.s: src/Items/Potions/Potion.cpp.s
.PHONY : src/Items/Potions/Potion.s

# target to generate assembly for a file
src/Items/Potions/Potion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Potions/Potion.cpp.s
.PHONY : src/Items/Potions/Potion.cpp.s

src/Items/Weapons/Frostforged.o: src/Items/Weapons/Frostforged.cpp.o
.PHONY : src/Items/Weapons/Frostforged.o

# target to build an object file
src/Items/Weapons/Frostforged.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Frostforged.cpp.o
.PHONY : src/Items/Weapons/Frostforged.cpp.o

src/Items/Weapons/Frostforged.i: src/Items/Weapons/Frostforged.cpp.i
.PHONY : src/Items/Weapons/Frostforged.i

# target to preprocess a source file
src/Items/Weapons/Frostforged.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Frostforged.cpp.i
.PHONY : src/Items/Weapons/Frostforged.cpp.i

src/Items/Weapons/Frostforged.s: src/Items/Weapons/Frostforged.cpp.s
.PHONY : src/Items/Weapons/Frostforged.s

# target to generate assembly for a file
src/Items/Weapons/Frostforged.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Frostforged.cpp.s
.PHONY : src/Items/Weapons/Frostforged.cpp.s

src/Items/Weapons/Thunderfury.o: src/Items/Weapons/Thunderfury.cpp.o
.PHONY : src/Items/Weapons/Thunderfury.o

# target to build an object file
src/Items/Weapons/Thunderfury.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Thunderfury.cpp.o
.PHONY : src/Items/Weapons/Thunderfury.cpp.o

src/Items/Weapons/Thunderfury.i: src/Items/Weapons/Thunderfury.cpp.i
.PHONY : src/Items/Weapons/Thunderfury.i

# target to preprocess a source file
src/Items/Weapons/Thunderfury.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Thunderfury.cpp.i
.PHONY : src/Items/Weapons/Thunderfury.cpp.i

src/Items/Weapons/Thunderfury.s: src/Items/Weapons/Thunderfury.cpp.s
.PHONY : src/Items/Weapons/Thunderfury.s

# target to generate assembly for a file
src/Items/Weapons/Thunderfury.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Thunderfury.cpp.s
.PHONY : src/Items/Weapons/Thunderfury.cpp.s

src/Items/Weapons/Weapon.o: src/Items/Weapons/Weapon.cpp.o
.PHONY : src/Items/Weapons/Weapon.o

# target to build an object file
src/Items/Weapons/Weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Weapon.cpp.o
.PHONY : src/Items/Weapons/Weapon.cpp.o

src/Items/Weapons/Weapon.i: src/Items/Weapons/Weapon.cpp.i
.PHONY : src/Items/Weapons/Weapon.i

# target to preprocess a source file
src/Items/Weapons/Weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Weapon.cpp.i
.PHONY : src/Items/Weapons/Weapon.cpp.i

src/Items/Weapons/Weapon.s: src/Items/Weapons/Weapon.cpp.s
.PHONY : src/Items/Weapons/Weapon.s

# target to generate assembly for a file
src/Items/Weapons/Weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/Items/Weapons/Weapon.cpp.s
.PHONY : src/Items/Weapons/Weapon.cpp.s

src/PlayerClasses.o: src/PlayerClasses.cpp.o
.PHONY : src/PlayerClasses.o

# target to build an object file
src/PlayerClasses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/PlayerClasses.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/PlayerClasses.cpp.o
.PHONY : src/PlayerClasses.cpp.o

src/PlayerClasses.i: src/PlayerClasses.cpp.i
.PHONY : src/PlayerClasses.i

# target to preprocess a source file
src/PlayerClasses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/PlayerClasses.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/PlayerClasses.cpp.i
.PHONY : src/PlayerClasses.cpp.i

src/PlayerClasses.s: src/PlayerClasses.cpp.s
.PHONY : src/PlayerClasses.s

# target to generate assembly for a file
src/PlayerClasses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/PlayerClasses.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/PlayerClasses.cpp.s
.PHONY : src/PlayerClasses.cpp.s

src/driverDragonQuest.o: src/driverDragonQuest.cpp.o
.PHONY : src/driverDragonQuest.o

# target to build an object file
src/driverDragonQuest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/driverDragonQuest.cpp.o
.PHONY : src/driverDragonQuest.cpp.o

src/driverDragonQuest.i: src/driverDragonQuest.cpp.i
.PHONY : src/driverDragonQuest.i

# target to preprocess a source file
src/driverDragonQuest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/driverDragonQuest.cpp.i
.PHONY : src/driverDragonQuest.cpp.i

src/driverDragonQuest.s: src/driverDragonQuest.cpp.s
.PHONY : src/driverDragonQuest.s

# target to generate assembly for a file
src/driverDragonQuest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/driverDragonQuest.cpp.s
.PHONY : src/driverDragonQuest.cpp.s

src/enemies/Dragon.o: src/enemies/Dragon.cpp.o
.PHONY : src/enemies/Dragon.o

# target to build an object file
src/enemies/Dragon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Dragon.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Dragon.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Dragon.cpp.o
.PHONY : src/enemies/Dragon.cpp.o

src/enemies/Dragon.i: src/enemies/Dragon.cpp.i
.PHONY : src/enemies/Dragon.i

# target to preprocess a source file
src/enemies/Dragon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Dragon.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Dragon.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Dragon.cpp.i
.PHONY : src/enemies/Dragon.cpp.i

src/enemies/Dragon.s: src/enemies/Dragon.cpp.s
.PHONY : src/enemies/Dragon.s

# target to generate assembly for a file
src/enemies/Dragon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Dragon.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Dragon.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Dragon.cpp.s
.PHONY : src/enemies/Dragon.cpp.s

src/enemies/Goblin.o: src/enemies/Goblin.cpp.o
.PHONY : src/enemies/Goblin.o

# target to build an object file
src/enemies/Goblin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Goblin.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Goblin.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Goblin.cpp.o
.PHONY : src/enemies/Goblin.cpp.o

src/enemies/Goblin.i: src/enemies/Goblin.cpp.i
.PHONY : src/enemies/Goblin.i

# target to preprocess a source file
src/enemies/Goblin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Goblin.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Goblin.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Goblin.cpp.i
.PHONY : src/enemies/Goblin.cpp.i

src/enemies/Goblin.s: src/enemies/Goblin.cpp.s
.PHONY : src/enemies/Goblin.s

# target to generate assembly for a file
src/enemies/Goblin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Goblin.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Goblin.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Goblin.cpp.s
.PHONY : src/enemies/Goblin.cpp.s

src/enemies/Ogre.o: src/enemies/Ogre.cpp.o
.PHONY : src/enemies/Ogre.o

# target to build an object file
src/enemies/Ogre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Ogre.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Ogre.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Ogre.cpp.o
.PHONY : src/enemies/Ogre.cpp.o

src/enemies/Ogre.i: src/enemies/Ogre.cpp.i
.PHONY : src/enemies/Ogre.i

# target to preprocess a source file
src/enemies/Ogre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Ogre.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Ogre.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Ogre.cpp.i
.PHONY : src/enemies/Ogre.cpp.i

src/enemies/Ogre.s: src/enemies/Ogre.cpp.s
.PHONY : src/enemies/Ogre.s

# target to generate assembly for a file
src/enemies/Ogre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Ogre.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Ogre.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Ogre.cpp.s
.PHONY : src/enemies/Ogre.cpp.s

src/enemies/Robot.o: src/enemies/Robot.cpp.o
.PHONY : src/enemies/Robot.o

# target to build an object file
src/enemies/Robot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Robot.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Robot.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Robot.cpp.o
.PHONY : src/enemies/Robot.cpp.o

src/enemies/Robot.i: src/enemies/Robot.cpp.i
.PHONY : src/enemies/Robot.i

# target to preprocess a source file
src/enemies/Robot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Robot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Robot.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Robot.cpp.i
.PHONY : src/enemies/Robot.cpp.i

src/enemies/Robot.s: src/enemies/Robot.cpp.s
.PHONY : src/enemies/Robot.s

# target to generate assembly for a file
src/enemies/Robot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Robot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Robot.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Robot.cpp.s
.PHONY : src/enemies/Robot.cpp.s

src/enemies/Slime.o: src/enemies/Slime.cpp.o
.PHONY : src/enemies/Slime.o

# target to build an object file
src/enemies/Slime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Slime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Slime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Slime.cpp.o
.PHONY : src/enemies/Slime.cpp.o

src/enemies/Slime.i: src/enemies/Slime.cpp.i
.PHONY : src/enemies/Slime.i

# target to preprocess a source file
src/enemies/Slime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Slime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Slime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Slime.cpp.i
.PHONY : src/enemies/Slime.cpp.i

src/enemies/Slime.s: src/enemies/Slime.cpp.s
.PHONY : src/enemies/Slime.s

# target to generate assembly for a file
src/enemies/Slime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/src/enemies/Slime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/enemies/Slime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/enemies/Slime.cpp.s
.PHONY : src/enemies/Slime.cpp.s

src/players/Mage.o: src/players/Mage.cpp.o
.PHONY : src/players/Mage.o

# target to build an object file
src/players/Mage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Mage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Mage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Mage.cpp.o
.PHONY : src/players/Mage.cpp.o

src/players/Mage.i: src/players/Mage.cpp.i
.PHONY : src/players/Mage.i

# target to preprocess a source file
src/players/Mage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Mage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Mage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Mage.cpp.i
.PHONY : src/players/Mage.cpp.i

src/players/Mage.s: src/players/Mage.cpp.s
.PHONY : src/players/Mage.s

# target to generate assembly for a file
src/players/Mage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Mage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Mage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Mage.cpp.s
.PHONY : src/players/Mage.cpp.s

src/players/Rogue.o: src/players/Rogue.cpp.o
.PHONY : src/players/Rogue.o

# target to build an object file
src/players/Rogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Rogue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Rogue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Rogue.cpp.o
.PHONY : src/players/Rogue.cpp.o

src/players/Rogue.i: src/players/Rogue.cpp.i
.PHONY : src/players/Rogue.i

# target to preprocess a source file
src/players/Rogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Rogue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Rogue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Rogue.cpp.i
.PHONY : src/players/Rogue.cpp.i

src/players/Rogue.s: src/players/Rogue.cpp.s
.PHONY : src/players/Rogue.s

# target to generate assembly for a file
src/players/Rogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Rogue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Rogue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Rogue.cpp.s
.PHONY : src/players/Rogue.cpp.s

src/players/Warrior.o: src/players/Warrior.cpp.o
.PHONY : src/players/Warrior.o

# target to build an object file
src/players/Warrior.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Warrior.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Warrior.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Warrior.cpp.o
.PHONY : src/players/Warrior.cpp.o

src/players/Warrior.i: src/players/Warrior.cpp.i
.PHONY : src/players/Warrior.i

# target to preprocess a source file
src/players/Warrior.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Warrior.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Warrior.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Warrior.cpp.i
.PHONY : src/players/Warrior.cpp.i

src/players/Warrior.s: src/players/Warrior.cpp.s
.PHONY : src/players/Warrior.s

# target to generate assembly for a file
src/players/Warrior.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/players/Warrior.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/src/players/Warrior.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/players/Warrior.cpp.s
.PHONY : src/players/Warrior.cpp.s

tests/BattleTimeTest.o: tests/BattleTimeTest.cpp.o
.PHONY : tests/BattleTimeTest.o

# target to build an object file
tests/BattleTimeTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/tests/BattleTimeTest.cpp.o
.PHONY : tests/BattleTimeTest.cpp.o

tests/BattleTimeTest.i: tests/BattleTimeTest.cpp.i
.PHONY : tests/BattleTimeTest.i

# target to preprocess a source file
tests/BattleTimeTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/tests/BattleTimeTest.cpp.i
.PHONY : tests/BattleTimeTest.cpp.i

tests/BattleTimeTest.s: tests/BattleTimeTest.cpp.s
.PHONY : tests/BattleTimeTest.s

# target to generate assembly for a file
tests/BattleTimeTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runBattleTests.dir/build.make CMakeFiles/runBattleTests.dir/tests/BattleTimeTest.cpp.s
.PHONY : tests/BattleTimeTest.cpp.s

tests/EnemyTest.o: tests/EnemyTest.cpp.o
.PHONY : tests/EnemyTest.o

# target to build an object file
tests/EnemyTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/tests/EnemyTest.cpp.o
.PHONY : tests/EnemyTest.cpp.o

tests/EnemyTest.i: tests/EnemyTest.cpp.i
.PHONY : tests/EnemyTest.i

# target to preprocess a source file
tests/EnemyTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/tests/EnemyTest.cpp.i
.PHONY : tests/EnemyTest.cpp.i

tests/EnemyTest.s: tests/EnemyTest.cpp.s
.PHONY : tests/EnemyTest.s

# target to generate assembly for a file
tests/EnemyTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runEnemyTests.dir/build.make CMakeFiles/runEnemyTests.dir/tests/EnemyTest.cpp.s
.PHONY : tests/EnemyTest.cpp.s

tests/PlayerTests.o: tests/PlayerTests.cpp.o
.PHONY : tests/PlayerTests.o

# target to build an object file
tests/PlayerTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.o
.PHONY : tests/PlayerTests.cpp.o

tests/PlayerTests.i: tests/PlayerTests.cpp.i
.PHONY : tests/PlayerTests.i

# target to preprocess a source file
tests/PlayerTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.i
.PHONY : tests/PlayerTests.cpp.i

tests/PlayerTests.s: tests/PlayerTests.cpp.s
.PHONY : tests/PlayerTests.s

# target to generate assembly for a file
tests/PlayerTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.s
.PHONY : tests/PlayerTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runBattleTests"
	@echo "... runEnemyTests"
	@echo "... runPlayerTests"
	@echo "... src/BattleTime.o"
	@echo "... src/BattleTime.i"
	@echo "... src/BattleTime.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/Items/Armors/Armor.o"
	@echo "... src/Items/Armors/Armor.i"
	@echo "... src/Items/Armors/Armor.s"
	@echo "... src/Items/Armors/Dragonsbane.o"
	@echo "... src/Items/Armors/Dragonsbane.i"
	@echo "... src/Items/Armors/Dragonsbane.s"
	@echo "... src/Items/Armors/Obsidiansentinel.o"
	@echo "... src/Items/Armors/Obsidiansentinel.i"
	@echo "... src/Items/Armors/Obsidiansentinel.s"
	@echo "... src/Items/Items.o"
	@echo "... src/Items/Items.i"
	@echo "... src/Items/Items.s"
	@echo "... src/Items/Potions/GreaterHealthPotion.o"
	@echo "... src/Items/Potions/GreaterHealthPotion.i"
	@echo "... src/Items/Potions/GreaterHealthPotion.s"
	@echo "... src/Items/Potions/LesserHealthPotion.o"
	@echo "... src/Items/Potions/LesserHealthPotion.i"
	@echo "... src/Items/Potions/LesserHealthPotion.s"
	@echo "... src/Items/Potions/Potion.o"
	@echo "... src/Items/Potions/Potion.i"
	@echo "... src/Items/Potions/Potion.s"
	@echo "... src/Items/Weapons/Frostforged.o"
	@echo "... src/Items/Weapons/Frostforged.i"
	@echo "... src/Items/Weapons/Frostforged.s"
	@echo "... src/Items/Weapons/Thunderfury.o"
	@echo "... src/Items/Weapons/Thunderfury.i"
	@echo "... src/Items/Weapons/Thunderfury.s"
	@echo "... src/Items/Weapons/Weapon.o"
	@echo "... src/Items/Weapons/Weapon.i"
	@echo "... src/Items/Weapons/Weapon.s"
	@echo "... src/PlayerClasses.o"
	@echo "... src/PlayerClasses.i"
	@echo "... src/PlayerClasses.s"
	@echo "... src/driverDragonQuest.o"
	@echo "... src/driverDragonQuest.i"
	@echo "... src/driverDragonQuest.s"
	@echo "... src/enemies/Dragon.o"
	@echo "... src/enemies/Dragon.i"
	@echo "... src/enemies/Dragon.s"
	@echo "... src/enemies/Goblin.o"
	@echo "... src/enemies/Goblin.i"
	@echo "... src/enemies/Goblin.s"
	@echo "... src/enemies/Ogre.o"
	@echo "... src/enemies/Ogre.i"
	@echo "... src/enemies/Ogre.s"
	@echo "... src/enemies/Robot.o"
	@echo "... src/enemies/Robot.i"
	@echo "... src/enemies/Robot.s"
	@echo "... src/enemies/Slime.o"
	@echo "... src/enemies/Slime.i"
	@echo "... src/enemies/Slime.s"
	@echo "... src/players/Mage.o"
	@echo "... src/players/Mage.i"
	@echo "... src/players/Mage.s"
	@echo "... src/players/Rogue.o"
	@echo "... src/players/Rogue.i"
	@echo "... src/players/Rogue.s"
	@echo "... src/players/Warrior.o"
	@echo "... src/players/Warrior.i"
	@echo "... src/players/Warrior.s"
	@echo "... tests/BattleTimeTest.o"
	@echo "... tests/BattleTimeTest.i"
	@echo "... tests/BattleTimeTest.s"
	@echo "... tests/EnemyTest.o"
	@echo "... tests/EnemyTest.i"
	@echo "... tests/EnemyTest.s"
	@echo "... tests/PlayerTests.o"
	@echo "... tests/PlayerTests.i"
	@echo "... tests/PlayerTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

