# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001/CMakeFiles /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /class/classes/idaci001/final-project-dahme007-scun002-syou029-idaci001/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runPlayerTests

# Build rule for target.
runPlayerTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runPlayerTests
.PHONY : runPlayerTests

# fast build rule for target.
runPlayerTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/build
.PHONY : runPlayerTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/Mage.o: src/Mage.cpp.o
.PHONY : src/Mage.o

# target to build an object file
src/Mage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Mage.cpp.o
.PHONY : src/Mage.cpp.o

src/Mage.i: src/Mage.cpp.i
.PHONY : src/Mage.i

# target to preprocess a source file
src/Mage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Mage.cpp.i
.PHONY : src/Mage.cpp.i

src/Mage.s: src/Mage.cpp.s
.PHONY : src/Mage.s

# target to generate assembly for a file
src/Mage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Mage.cpp.s
.PHONY : src/Mage.cpp.s

src/PlayerClasses.o: src/PlayerClasses.cpp.o
.PHONY : src/PlayerClasses.o

# target to build an object file
src/PlayerClasses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.o
.PHONY : src/PlayerClasses.cpp.o

src/PlayerClasses.i: src/PlayerClasses.cpp.i
.PHONY : src/PlayerClasses.i

# target to preprocess a source file
src/PlayerClasses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.i
.PHONY : src/PlayerClasses.cpp.i

src/PlayerClasses.s: src/PlayerClasses.cpp.s
.PHONY : src/PlayerClasses.s

# target to generate assembly for a file
src/PlayerClasses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/PlayerClasses.cpp.s
.PHONY : src/PlayerClasses.cpp.s

src/Rogue.o: src/Rogue.cpp.o
.PHONY : src/Rogue.o

# target to build an object file
src/Rogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Rogue.cpp.o
.PHONY : src/Rogue.cpp.o

src/Rogue.i: src/Rogue.cpp.i
.PHONY : src/Rogue.i

# target to preprocess a source file
src/Rogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Rogue.cpp.i
.PHONY : src/Rogue.cpp.i

src/Rogue.s: src/Rogue.cpp.s
.PHONY : src/Rogue.s

# target to generate assembly for a file
src/Rogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Rogue.cpp.s
.PHONY : src/Rogue.cpp.s

src/Warrior.o: src/Warrior.cpp.o
.PHONY : src/Warrior.o

# target to build an object file
src/Warrior.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Warrior.cpp.o
.PHONY : src/Warrior.cpp.o

src/Warrior.i: src/Warrior.cpp.i
.PHONY : src/Warrior.i

# target to preprocess a source file
src/Warrior.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Warrior.cpp.i
.PHONY : src/Warrior.cpp.i

src/Warrior.s: src/Warrior.cpp.s
.PHONY : src/Warrior.s

# target to generate assembly for a file
src/Warrior.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/src/Warrior.cpp.s
.PHONY : src/Warrior.cpp.s

tests/PlayerTests.o: tests/PlayerTests.cpp.o
.PHONY : tests/PlayerTests.o

# target to build an object file
tests/PlayerTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.o
.PHONY : tests/PlayerTests.cpp.o

tests/PlayerTests.i: tests/PlayerTests.cpp.i
.PHONY : tests/PlayerTests.i

# target to preprocess a source file
tests/PlayerTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.i
.PHONY : tests/PlayerTests.cpp.i

tests/PlayerTests.s: tests/PlayerTests.cpp.s
.PHONY : tests/PlayerTests.s

# target to generate assembly for a file
tests/PlayerTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runPlayerTests.dir/build.make CMakeFiles/runPlayerTests.dir/tests/PlayerTests.cpp.s
.PHONY : tests/PlayerTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... runPlayerTests"
	@echo "... src/Mage.o"
	@echo "... src/Mage.i"
	@echo "... src/Mage.s"
	@echo "... src/PlayerClasses.o"
	@echo "... src/PlayerClasses.i"
	@echo "... src/PlayerClasses.s"
	@echo "... src/Rogue.o"
	@echo "... src/Rogue.i"
	@echo "... src/Rogue.s"
	@echo "... src/Warrior.o"
	@echo "... src/Warrior.i"
	@echo "... src/Warrior.s"
	@echo "... tests/PlayerTests.o"
	@echo "... tests/PlayerTests.i"
	@echo "... tests/PlayerTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

